### PR TITLE
Make tests succeed in Rails 5

### PR DESCRIPTION
**Pull request by jenskdsgn**
Thanks @cebartling for the actual fix in this PR https://github.com/iostat/eav_hashes/pull/8

Issue https://github.com/iostat/eav_hashes/issues/7

### CODE REVIEW

**Review by cebartling — APPROVED** [review]

**Comment by jenskdsgn** [comment]
@iostat Can you give feedback and/or merge this PR?

**Comment by iostat** [comment]
Hey, thanks for the PRs!
I need to set up a Ruby environment to push this to Rubygems, so give me a few hours to get that done. In the meantime, I hope it's ok for you to just depend on the branch.

**Comment by jenskdsgn** [comment]
@iostat thank you!

**Comment by iostat** [comment]
Hey! Just pushed to RubyGems as `1.1.0`, and added both of you to the README! Thanks again for submitting these PRs!

**Pull request merged**
